version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "jhipster_db"
      POSTGRES_USER: "jhipster"
      POSTGRES_PASSWORD: "jhipster_pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - jhipster-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  jhipster-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'db-data'
